package com.isaiahvonrundsedt.testflight.ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class Configurator implements ActionListener {

    private JFrame thisFrame;

    private JTextField pageFrameField;
    private JTextField requestAmountField;
    private JComboBox methodBox;
    private JButton okButton;
    private JPanel root;

    public Configurator(JFrame frame) {
        $$$setupUI$$$();
        thisFrame = frame;
        okButton.addActionListener(this);
    }

    public JPanel getRoot() {
        return root;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        int frames = Integer.parseInt(pageFrameField.getText());
        int requests = Integer.parseInt(requestAmountField.getText());

        int method = methodBox.getSelectedIndex();

        if (frames > 10 || requests > 50) {
            JOptionPane.showMessageDialog(root, "Unsupported value.");
        } else {
            thisFrame.dispose();

            JFrame frame = new JFrame("TestFlight");
            frame.setContentPane(new Main(frames, requests, method).getRoot());
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.pack();
            frame.setVisible(true);
        }
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Ubuntu", Font.BOLD, 18, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("TestFlight Configurator");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(24, 48, 0, 0);
        root.add(label1, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(24, 48, 0, 48);
        root.add(panel1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Enter  Page Frame Size:");
        panel1.add(label2);
        pageFrameField = new JTextField();
        pageFrameField.setColumns(10);
        panel1.add(pageFrameField);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 48, 0, 48);
        root.add(panel2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Enter Request Amount:");
        panel2.add(label3);
        requestAmountField = new JTextField();
        requestAmountField.setColumns(10);
        panel2.add(requestAmountField);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(0, 48, 0, 48);
        root.add(panel3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Select method:");
        panel3.add(label4);
        methodBox = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("LRU - Least Recently Used");
        defaultComboBoxModel1.addElement("FIFO - First-In, First-Out");
        methodBox.setModel(defaultComboBoxModel1);
        panel3.add(methodBox);
        okButton = new JButton();
        okButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(24, 72, 48, 72);
        root.add(okButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }

}
